<%
  local_env = {}
  if Rails.env.development? || Rails.env.test?
    branch = %x[git rev-parse --abbrev-ref HEAD].strip rescue nil
    branch = branch.gsub('/', '_')
    local_env = YAML.load_file("#{Rails.root}/local_env.yml").dig(Rails.env) || {}

    if(local_env.dig('devdb') != nil)
      branch = local_env.dig('devdb')
    end
  end
%>

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= local_env.dig('database', 'username') %>
  password: <%= local_env.dig('database', 'password') %>
  <% if(local_env.dig('database', 'host') != nil) %>
  host:  <%= local_env.dig('database', 'host') %>
  <% end %>
  <% if(local_env.dig('database', 'port') != nil) %>
  port:  <%= local_env.dig('database', 'port') %>
  <% end %>

development:
  <<: *default
  database: candlelight_development

test:
  <<: *default
  database: candlelight_test

production:
  <<: *default
  database: candlelight_production
  username: candlelight
  password: <%= ENV['CANDLELIGHT_DATABASE_PASSWORD'] %>
